version: '3.8'

services:
  ai-tts:
    build: .
    container_name: ai-ASR
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "5016:5016"
    volumes:
      - ./src:/app/src
      - ./models:/app/models
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
